### ISSUE TITLE
Could not open database

### ISSUE THREAD

**Issue by ElHappy** [graviton57/SqliteAndroid#1]
I follow the **How to use** steps and put the _System.loadLibrary()_ on my constructor of the database helper, work great using trigonometrics on the query I needed, but had problems with some querys when I need to search info, I think maybe was because I had the database before change the library of sqlite.

After I uninstall the application and try again, I can't start the application I receive the error that is failed to open the database.

It's something more I need to do or know what can be the problem?

**UPDATE:**
The problem seems to be the database is not created in the internal memory, never access to onCreate and onUpgrade, but I don't know why, if I change the library for the default on android it's works without problem (just not the trigonometrics).

**Logcat:**
```
2019-01-09 13:51:47.428 2941-2941/com.aibec.ondex E/SQLiteLog: (14) cannot open file at line 36227 of [8d3a7ea6c5]
2019-01-09 13:51:47.428 2941-2941/com.aibec.ondex E/SQLiteLog: (14) os_unix.c:36227: (2) open(//SQLiteTapscan.db) - 
2019-01-09 13:51:47.438 2941-2941/com.aibec.ondex E/SQLiteDatabase: Failed to open database 'SQLiteTapscan.db'.
    org.sqlite.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
        at org.sqlite.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at org.sqlite.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:225)
        at org.sqlite.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
        at org.sqlite.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:501)
        at org.sqlite.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:190)
        at org.sqlite.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:182)
        at org.sqlite.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
        at org.sqlite.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
        at org.sqlite.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:698)
        at org.sqlite.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:721)
        at org.sqlite.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:228)
        at org.sqlite.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:192)
        at com.aibec.ondex.TapscanDBHelper.getPapeletasToUpload(TapscanDBHelper.java:230)
        at com.aibec.ondex.Ovampas.onCreate(Ovampas.java:193)
        at android.app.Activity.performCreate(Activity.java:7003)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by mddanishansari** [comment]
In the class where you are opening the database try adding this static block

```java
static {
	System.loadLibrary("sqliteX");
	System.loadLibrary("sqlitefunctions");
}
```

or in Kotlin 


```kotlin
companion object {
	init {
		System.loadLibrary("sqliteX")
		System.loadLibrary("sqlitefunctions")
	}
}
```
